"""
Django settings for amazon_clone project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config # <-- ИМПОРТИРОВАНО: Для безопасных переменных окружения
import dj_database_url # <-- ИМПОРТИРОВАНО: Для подключения PostgreSQL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# -------------------------------------------------------------------
# НАСТРОЙКИ ДЛЯ ПРОДАКШЕНА (Render)
# -------------------------------------------------------------------

# 1. SECRET_KEY: Берется из переменной окружения (файла .env или настроек Render)
# Если переменная не найдена, используется старый ключ (ТОЛЬКО ДЛЯ ЛОКАЛЬНОЙ ПРОВЕРКИ!)
SECRET_KEY = config('SECRET_KEY')

# 2. DEBUG: Берется из переменной окружения. Локально = True, на Render = False
DEBUG = config('DEBUG', default=True, cast=bool)


# 3. ALLOWED_HOSTS: Должен разрешать домен Render
ALLOWED_HOSTS = ['*']
if not DEBUG:
    # Здесь должен быть домен Render (например, .onrender.com)
    # Звездочка (*) разрешит все субдомены
    ALLOWED_HOSTS = ['.onrender.com']


# -------------------------------------------------------------------
# Application definition
# -------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Ваши приложения
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amazon_clone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amazon_clone.wsgi.application'


# -------------------------------------------------------------------
# Database (ПЕРЕНАСТРОЙКА ДЛЯ PostgreSQL)
# -------------------------------------------------------------------
# Это автоматически переключит БД на PostgreSQL, если Render предоставит ей DATABASE_URL.
# Локально будет использоваться SQLite.

DATABASES = {
    'default': dj_database_url.config(
        # Использует SQLite3 по умолчанию, если DATABASE_URL не задан (т.е. локально)
        default=f'sqlite:///{os.path.join(BASE_DIR, "db.sqlite3")}',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# -------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# -------------------------------------------------------------------

STATIC_URL = 'static/'
# STATIC_ROOT нужен для Render, чтобы собрать статику в одну папку
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CART_SESSION_ID = 'cart' # Ключ, по которому корзина хранится в сессии


# -------------------------------------------------------------------
# АВТОРИЗАЦИЯ
# -------------------------------------------------------------------

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'